// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Apimanagement.Models
{

    /// <summary>
    /// Defines values for ApiType.
    /// </summary>
    public static class ApiType
    {
        public const string Http = "http";
        public const string Soap = "soap";
    }
}
