// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Apimanagement.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Control Plane Apis version constraint for the API Management service.
    /// </summary>
    public partial class ApiVersionConstraint
    {
        /// <summary>
        /// Initializes a new instance of the ApiVersionConstraint class.
        /// </summary>
        public ApiVersionConstraint()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApiVersionConstraint class.
        /// </summary>
        /// <param name="minApiVersion">Limit control plane API calls to API
        /// Management service with version equal to or newer than this
        /// value.</param>
        public ApiVersionConstraint(string minApiVersion = default(string))
        {
            MinApiVersion = minApiVersion;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets limit control plane API calls to API Management
        /// service with version equal to or newer than this value.
        /// </summary>
        [JsonProperty(PropertyName = "minApiVersion")]
        public string MinApiVersion { get; set; }

    }
}
