// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Apimanagement.Models
{

    /// <summary>
    /// Defines values for AppType.
    /// </summary>
    public static class AppType
    {
        /// <summary>
        /// User create request was sent by legacy developer portal.
        /// </summary>
        public const string Portal = "portal";
        /// <summary>
        /// User create request was sent by new developer portal.
        /// </summary>
        public const string DeveloperPortal = "developerPortal";
    }
}
