// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Apimanagement.Models
{

    /// <summary>
    /// Defines values for ConnectivityStatusType.
    /// </summary>
    public static class ConnectivityStatusType
    {
        public const string Initializing = "initializing";
        public const string Success = "success";
        public const string Failure = "failure";
    }
}
