// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Apimanagement.Models
{

    /// <summary>
    /// Defines values for HttpCorrelationProtocol.
    /// </summary>
    public static class HttpCorrelationProtocol
    {
        /// <summary>
        /// Do not read and inject correlation headers.
        /// </summary>
        public const string None = "None";
        /// <summary>
        /// Inject Request-Id and Request-Context headers with request
        /// correlation data. See
        /// https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/HttpCorrelationProtocol.md.
        /// </summary>
        public const string Legacy = "Legacy";
        /// <summary>
        /// Inject Trace Context headers. See
        /// https://w3c.github.io/trace-context.
        /// </summary>
        public const string W3C = "W3C";
    }
}
