// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Apimanagement.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Lists Regions operation response details.
    /// </summary>
    public partial class RegionListResult
    {
        /// <summary>
        /// Initializes a new instance of the RegionListResult class.
        /// </summary>
        public RegionListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RegionListResult class.
        /// </summary>
        /// <param name="value">Lists of Regions.</param>
        /// <param name="count">Total record count number across all
        /// pages.</param>
        /// <param name="nextLink">Next page link if any.</param>
        public RegionListResult(IList<RegionContract> value = default(IList<RegionContract>), long? count = default(long?), string nextLink = default(string))
        {
            Value = value;
            Count = count;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets lists of Regions.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<RegionContract> Value { get; set; }

        /// <summary>
        /// Gets or sets total record count number across all pages.
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public long? Count { get; set; }

        /// <summary>
        /// Gets or sets next page link if any.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; set; }

    }
}
