// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Apimanagement.Models
{

    /// <summary>
    /// Defines values for SoapApiType.
    /// </summary>
    public static class SoapApiType
    {
        /// <summary>
        /// Imports a SOAP API having a RESTful front end.
        /// </summary>
        public const string SoapToRest = "http";
        /// <summary>
        /// Imports the Soap API having a SOAP front end.
        /// </summary>
        public const string SoapPassThrough = "soap";
    }
}
