// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Apimanagement.Models
{

    /// <summary>
    /// Defines values for State.
    /// </summary>
    public static class State
    {
        /// <summary>
        /// The issue is proposed.
        /// </summary>
        public const string Proposed = "proposed";
        /// <summary>
        /// The issue is opened.
        /// </summary>
        public const string Open = "open";
        /// <summary>
        /// The issue was removed.
        /// </summary>
        public const string Removed = "removed";
        /// <summary>
        /// The issue is now resolved.
        /// </summary>
        public const string Resolved = "resolved";
        /// <summary>
        /// The issue was closed.
        /// </summary>
        public const string Closed = "closed";
    }
}
