// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Apimanagement
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for PolicyDescription.
    /// </summary>
    public static partial class PolicyDescriptionExtensions
    {
            /// <summary>
            /// Lists all policy descriptions.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='resourceGroupName'>
            /// The name of the resource group.
            /// </param>
            /// <param name='serviceName'>
            /// The name of the API Management service.
            /// </param>
            /// <param name='scope'>
            /// Policy scope. Possible values include: 'Tenant', 'Product', 'Api',
            /// 'Operation', 'All'
            /// </param>
            public static PolicyDescriptionCollection ListByService(this IPolicyDescription operations, string resourceGroupName, string serviceName, PolicyScopeContract? scope = default(PolicyScopeContract?))
            {
                return operations.ListByServiceAsync(resourceGroupName, serviceName, scope).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Lists all policy descriptions.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='resourceGroupName'>
            /// The name of the resource group.
            /// </param>
            /// <param name='serviceName'>
            /// The name of the API Management service.
            /// </param>
            /// <param name='scope'>
            /// Policy scope. Possible values include: 'Tenant', 'Product', 'Api',
            /// 'Operation', 'All'
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<PolicyDescriptionCollection> ListByServiceAsync(this IPolicyDescription operations, string resourceGroupName, string serviceName, PolicyScopeContract? scope = default(PolicyScopeContract?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ListByServiceWithHttpMessagesAsync(resourceGroupName, serviceName, scope, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
